n=int(input("Qual o primeiro valor : "))
n1=int(input("Qual o segundo valor : "))
print("Soma dos valores:",n,"+",n1,"=", n1+n)
print("Diferença entre os valores é de :",n,"-",n1,"=",n - n1)
print("Multiplicaçao entre os valores: ",n,"*",n1,"=",n*n1)
